# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "jammed"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sean Lerner", "Rob Young", "Mike Chlipala"]
  s.date = "2012-04-20"
  s.description = "Jammed wraps the This Is My Jam API. More information about the This Is My Jam API can be found on their website (http://www.thisismyjam.com/developers)."
  s.email = ["seanslerner@gmail.com"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".gitignore",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "examples/basics.rb",
    "lib/jammed.rb",
    "lib/jammed/base.rb",
    "lib/jammed/followers.rb",
    "lib/jammed/following.rb",
    "lib/jammed/jams.rb",
    "lib/jammed/likes.rb",
    "lib/jammed/people_search.rb",
    "lib/jammed/person.rb",
    "lib/jammed/popular_jams.rb",
    "lib/jammed/suggested_people.rb",
    "lib/jammed/user.rb",
    "lib/jammed/version.rb",
    "spec/jammed/base_spec.rb",
    "spec/jammed/followers_spec.rb",
    "spec/jammed/following_spec.rb",
    "spec/jammed/jams_spec.rb",
    "spec/jammed/likes_spec.rb",
    "spec/jammed/people_search_spec.rb",
    "spec/jammed/person_spec.rb",
    "spec/jammed/popular_jams_spec.rb",
    "spec/jammed/suggested_people_spec.rb",
    "spec/jammed/user_spec.rb",
    "spec/sample_responses/followers.json",
    "spec/sample_responses/followers_affinity.json",
    "spec/sample_responses/followers_date.json",
    "spec/sample_responses/followers_name.json",
    "spec/sample_responses/following.json",
    "spec/sample_responses/following_affinity.json",
    "spec/sample_responses/following_date.json",
    "spec/sample_responses/following_name.json",
    "spec/sample_responses/jams.json",
    "spec/sample_responses/jams_past.json",
    "spec/sample_responses/likes.json",
    "spec/sample_responses/likes_current.json",
    "spec/sample_responses/likes_past.json",
    "spec/sample_responses/person.json",
    "spec/sample_responses/popular.json",
    "spec/sample_responses/search_artist.json",
    "spec/sample_responses/search_name.json",
    "spec/sample_responses/search_track.json",
    "spec/sample_responses/suggested_people.json",
    "spec/spec_helper.rb"
  ]
  s.homepage = "https://github.com/seanslerner/Jammed"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "A Ruby wrapper for This Is My Jam's API"
  s.test_files = ["spec/jammed/base_spec.rb", "spec/jammed/followers_spec.rb", "spec/jammed/following_spec.rb", "spec/jammed/jams_spec.rb", "spec/jammed/likes_spec.rb", "spec/jammed/people_search_spec.rb", "spec/jammed/person_spec.rb", "spec/jammed/popular_jams_spec.rb", "spec/jammed/suggested_people_spec.rb", "spec/jammed/user_spec.rb", "spec/sample_responses/followers.json", "spec/sample_responses/followers_affinity.json", "spec/sample_responses/followers_date.json", "spec/sample_responses/followers_name.json", "spec/sample_responses/following.json", "spec/sample_responses/following_affinity.json", "spec/sample_responses/following_date.json", "spec/sample_responses/following_name.json", "spec/sample_responses/jams.json", "spec/sample_responses/jams_past.json", "spec/sample_responses/likes.json", "spec/sample_responses/likes_current.json", "spec/sample_responses/likes_past.json", "spec/sample_responses/person.json", "spec/sample_responses/popular.json", "spec/sample_responses/search_artist.json", "spec/sample_responses/search_name.json", "spec/sample_responses/search_track.json", "spec/sample_responses/suggested_people.json", "spec/spec_helper.rb"]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0.8.2"])
      s.add_development_dependency(%q<rake>, [">= 0.8.7"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_development_dependency(%q<rspec>, [">= 2.9.0"])
      s.add_development_dependency(%q<webmock>, [">= 1.8.6"])
    else
      s.add_dependency(%q<httparty>, [">= 0.8.2"])
      s.add_dependency(%q<rake>, [">= 0.8.7"])
      s.add_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_dependency(%q<rspec>, [">= 2.9.0"])
      s.add_dependency(%q<webmock>, [">= 1.8.6"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0.8.2"])
    s.add_dependency(%q<rake>, [">= 0.8.7"])
    s.add_dependency(%q<jeweler>, [">= 1.8.3"])
    s.add_dependency(%q<rspec>, [">= 2.9.0"])
    s.add_dependency(%q<webmock>, [">= 1.8.6"])
  end
end

